included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - DerivedData
  - .tn-profiles

reporter: "xcode"

analyzer_rules:
  - unused_declaration
  - unused_import
  - explicit_self

disabled_rules:
  - trailing_comma
  - opening_brace

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_object_literal
  - duplicate_imports
  - empty_count
  - empty_string
  - explicit_init
  - file_name
  - file_name_no_space
  - first_where
  - force_unwrapping
  - implicit_return
  - let_var_whitespace
  - modifier_order
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - shorthand_optional_binding
  - sorted_imports
  - strict_fileprivate
  - switch_case_alignment
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

# Severity/threshold tuning
line_length:
  warning: 120
  error: 140
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 600
  error: 1200

cyclomatic_complexity:
  warning: 15
  error: 20

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - fd
    - tn

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: false

force_cast:
  severity: warning

force_unwrapping:
  severity: warning
